name: Create PR with Atlas Operator Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  create-release-branch:
    permissions:
      contents: write
    name: Create Release branch
    runs-on: ubuntu-latest
    steps:
      - name: Clone repositories
        run: |
          mkdir operator
          cd operator
          git clone https://github.com/mongodb/mongodb-atlas-kubernetes.git
          cd ..
          mkdir helm
          cd helm
          git clone https://github.com/Sugar-pack/helm-charts.git
          cd ..
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy crd template files
        run: |
          cp -a operator/mongodb-atlas-kubernetes/bundle/manifests/atlas.mongodb.com_atlasbackuppolicies.yaml helm/helm-charts/charts/atlas-operator-crds/templates
          cp -a operator/mongodb-atlas-kubernetes/bundle/manifests/atlas.mongodb.com_atlasbackupschedules.yaml helm/helm-charts/charts/atlas-operator-crds/templates
          cp -a operator/mongodb-atlas-kubernetes/bundle/manifests/atlas.mongodb.com_atlasdatabaseusers.yaml helm/helm-charts/charts/atlas-operator-crds/templates
          cp -a operator/mongodb-atlas-kubernetes/bundle/manifests/atlas.mongodb.com_atlasdeployments.yaml helm/helm-charts/charts/atlas-operator-crds/templates
          cp -a operator/mongodb-atlas-kubernetes/bundle/manifests/atlas.mongodb.com_atlasprojects.yaml helm/helm-charts/charts/atlas-operator-crds/templates
          cp -a operator/mongodb-atlas-kubernetes/bundle/manifests/atlas.mongodb.com_atlasteams.yaml helm/helm-charts/charts/atlas-operator-crds/templates
      - name: Edit versions in chart files
        id: set-version
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          cd helm/helm-charts/charts/atlas-operator-crds
          sed -i -r 's/version:....../version: '"$VERSION"'/g' Chart.yaml
          sed -i -r 's/appVersion:....../appVersion: '"$VERSION"'/g' Chart.yaml
          cd ..
          cd atlas-operator
          sed -i -r 's/version:.\x22.....\x22/version: \x22'"$VERSION"'\x22/g' Chart.yaml
          sed -i -r 's/version:......$/version: '"$VERSION"'/g' Chart.yaml
          sed -i -r 's/appVersion:....../appVersion: '"$VERSION"'/g' Chart.yaml
          cd ..
      - name: Checkout operator branch
        run: |
          cd operator/mongodb-atlas-kubernetes
          git fetch
          git branch -v -a
          git checkout post-release-helm
          cd ../..
      - name: Set branch name
        id: git-config
        run: |
          echo ${{ steps.set-version.outputs.version }}
          branch="atlas-operator-release-${{ steps.set-version.outputs.version }}"
          echo "branch=$branch" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push branch
        run: |
          cp operator/mongodb-atlas-kubernetes/.github/actions/push-files/entrypoint.sh helm/helm-charts
          cd helm/helm-charts
          chmod +x entrypoint.sh
          git checkout -b ${{ steps.git-config.outputs.branch }}
          gh auth setup-git
          git push origin ${{ steps.git-config.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push crds chart
        run: |
          cd helm/helm-charts
          git add .
          git fetch origin ${{ steps.git-config.outputs.branch }}
          git init
          ./entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION_BRANCH: ${{ steps.git-config.outputs.branch }}
          PATH_TO_COMMIT: "charts/atlas-operator-crds/Chart.yaml"
      - name: Commit and push operator chart
        run: |
          cd helm/helm-charts
          ./entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION_BRANCH: ${{ steps.git-config.outputs.branch }}
          PATH_TO_COMMIT: "charts/atlas-operator/Chart.yaml"
      - name: Commit and push crd templates
        run: |
          cd helm/helm-charts
          ./entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DESTINATION_BRANCH: ${{ steps.git-config.outputs.branch }}
          PATH_TO_COMMIT: "charts/atlas-operator-crds/templates"
      - name: create pull request
        run: |
          cd helm/helm-charts
          gh pr create --title "Update atlas operator version to ${{ steps.set-version.outputs.version }}" \
          --body "Update atlas operator version to ${{ steps.set-version.outputs.version }}" \
          --base branch-for-pr --head ${{ steps.git-config.outputs.branch }} \
          --repo Sugar-pack/helm-charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}